name: jsettlers # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '2.6.00' # just for humans, typically '1.2+git' or '1.3.2'
summary:  A desktop client-server version of Settlers of Catan in Java
description: |
   JSettlers is a Java version of the board game Settlers of Catan written in Java. This client-server system supports multiple simultaneous games between people and computer-controlled opponents. Initially created as an AI research project.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  jsettlers_icon.png
title: Jsettlers

apps:
  jsettlers:
    command: startjsett
parts:
  jsettlers:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      jsettlers: build/
      jsettlers.1: man/man1/

architectures:
  - build-on: amd64

